CREATE TABLE qts_records(qts_autoid INT NOT NULL AUTO_INCREMENT,
						qts_secuid BIGINT NOT NULL,
						qts_account BIGINT NOT NULL,
						qts_strategyid INT NOT NULL,
						qts_orderid BIGINT NOT NULL,
						qts_algoid BIGINT NOT NULL,
						qts_algoindex BIGINT NOT NULL,
						qts_parentid BIGINT NOT NULL,
						qts_code BIGINT NOT NULL,
						qts_action INT NOT NULL,
						qts_paction INT NOT NULL,
						qts_status INT NOT NULL,
						qts_prevstatus INT NOT NULL,
						qts_oprice BIGINT NOT NULL,
						qts_iprice BIGINT NOT NULL,
						qts_ovolume BIGINT NOT NULL,
						qts_ivolume BIGINT NOT NULL,
						qts_otime BIGINT NOT NULL,
						qts_itime BIGINT NOT NULL,
						qts_property INT NOT NULL,
						qts_direction INT NOT NULL,
						qts_canceled INT NOT NULL,
						qts_userid INT NOT NULL,
						qts_refid BIGINT NOT NULL,
						qts_sessionid INT NOT NULL,
						qts_source INT NOT NULL,
						qts_ss INT NOT NULL,
						qts_gw INT NOT NULL,
						PRIMARY KEY(qts_autoid));
						
ALTER TABLE qts_records	ADD	UNIQUE(qts_orderid);
ALTER TABLE qts_records ADD INDEX qts_records_index(qts_account,qts_algoid,qts_parentid);