#coding=utf-8
import string

QTS_DEFAULT_LOG_KEY = 'default_log'
QTS_CFG_KEY_TYPE = 'qts_type'
QTS_CFG_KEY_SUBTYPE = 'qts_subtype'
QTS_CFG_KEY_SECUID = 'qts_secuid'
QTS_CFG_KEY_OBJID = 'qts_objid'
QTS_CFG_KEY_NAME = 'qts_name'
QTS_CFG_KEY_VERSION = 'qts_version'
QTS_CFG_KEY_PATH = 'qts_path'
QTS_CFG_KEY_SUBPATH = 'qts_subpath'
QTS_CFG_KEY_FILE = 'qts_file'
QTS_CFG_KEY_FUN	= 'qts_fun'
QTS_CFG_KEY_CFG = 'qts_cfg'
QTS_CFG_KEY_LOG = 'qts_log'
QTS_CFG_KEY_ALGOES = 'qts_algoes'
QTS_CFG_KEY_FILTERS = 'qts_filters'
QTS_CFG_KEY_CHECKS = 'qts_checks'
QTS_CFG_KEY_CALCULATES = 'qts_calculates'
QTS_CFG_KEY_LOGICS = 'qts_logics'
QTS_CFG_KEY_BUFFSIZE = 'qts_buffsize'
QTS_CFG_KEY_ADDRESS	= 'qts_address'
QTS_CFG_KEY_PORT = 'qts_port'
QTS_CFG_KEY_HEART = 'qts_heart'
QTS_CFG_KEY_LIFE = 'qts_life'
QTS_CFG_KEY_INSTID	= 'qts_instid'
QTS_CFG_KEY_OWNERID	= 'qts_ownerid'
QTS_CFG_KEY_INSTRUMENT = 'qts_instrument'
QTS_CFG_KEY_PARAMETER = 'qts_parameter'
QTS_CFG_KEY_COMMENT	= 'qts_comment'
QTS_CFG_KEY_COMMAND	= 'qts_command'
QTS_CFG_KEY_TASK = 'qts_task'
QTS_CFG_KEY_MINORDERID = 'qts_minorderid'
QTS_CFG_KEY_MAXORDERID = 'qts_maxorderid'
QTS_CFG_KEY_ORDERIDSTEP = 'qts_orderidstep'
QTS_CFG_KEY_STATUS = 'qts_status'
QTS_CFG_KEY_ACCOUNT = 'qts_account'
QTS_CFG_KEY_PROTOPATH = 'qts_protopath'
QTS_CFG_KEY_PROTOFILE = 'qts_protofile'
QTS_CFG_KEY_TRADEFILE = 'qts_tradefile'
QTS_CFG_KEY_TRADEFUN = 'qts_tradefun'
QTS_CFG_KEY_MKFILE = 'qts_mkfile'
QTS_CFG_KEY_MKFUN = 'qts_mkfun'
QTS_CFG_KEY_EXFILE = 'qts_exfile'
QTS_CFG_KEY_EXFUN = 'qts_exfun'
QTS_CFG_KEY_BACKUP = 'qts_backup'
QTS_CFG_KEY_LOADER = 'qts_loader'
QTS_CFG_KEY_LOADETYPE = 'qts_loadtype'
QTS_CFG_KEY_LOGMESSAGE = 'qts_logmessage'
QTS_CFG_KEY_LOGDEBUG = 'qts_logdebug'
QTS_CFG_KEY_LOGERROR = 'qts_logerror'
QTS_CFG_KEY_LOGWARNING = 'qts_logwarning'
QTS_CFG_KEY_TRACEMESSAGE = 'qts_tracemessage'
QTS_CFG_KEY_TRACEDEBUG = 'qts_tracedebug'
QTS_CFG_KEY_TRACEERROR = 'qts_traceerror'
QTS_CFG_KEY_TRACEWARNING = 'qts_tracewarning'
QTS_CFG_KEY_PARAMETERSAVE = 'qts_parametersave'
QTS_CFG_KEY_VIRTUALHOST = 'qts_virtualhost'
QTS_CFG_KEY_EXCHANGE = 'qts_exchange'
QTS_CFG_KEY_QUEUE = 'qts_queue'
QTS_CFG_KEY_ROUTINGKEY = 'qts_routingkey'
QTS_CFG_KEY_EXTYPE = 'qts_extype'
QTS_CFG_KEY_USR = 'qts_usr'
QTS_CFG_KEY_PSW = 'qts_psw'
QTS_CFG_KEY_DATA_PATH = 'qts_dpath'
QTS_CFG_KEY_BEGIN_DATE = 'qts_bdate'
QTS_CFG_KEY_BEGIN_TIME = 'qts_btime'
QTS_CFG_KEY_END_DATE = 'qts_edate'
QTS_CFG_KEY_END_TIME = 'qts_etime'
QTS_CFG_KEY_MATCH_MODE = 'qts_match_mode'
QTS_CFG_KEY_MONITOR_TIME = 'qts_monitortime'
QTS_CFG_KEY_THDMULTI = 'qts_thdmulti'
QTS_CFG_KEY_POSITION = 'qts_position'
QTS_CFG_KEY_RECORD = 'qts_record'
QTS_CFG_KEY_CHECKSECUID = 'qts_checksecuid'
QTS_CFG_KEY_TESTMODE = 'qts_test_mode'
QTS_CFG_KEY_TESTDELAY = 'qts_test_delay'
QTS_CFG_KEY_TESTCOUNT = 'qts_test_count'
QTS_DATA_TO_GW = 'qts_data_to_gw'
QTS_DATA_TO_GUI = 'qts_data_to_gui'
QTS_RECORD_TO_REMOTE = 'qts_record_to_remote'
QTS_POSITION_TO_REMOTE = 'qts_position_to_remote'
QTS_ACCOUNT_TO_REMOTE = 'qts_account_to_remote'
QTS_CFG_KEY_CSVFLAG = 'qts_csv_flag'

QTS_CFG_GROUP_CFG = 'QTS_Cfg'
QTS_CFG_GROUP_APP = 'QTS_App'
QTS_CFG_GROUP_CONTEXT = 'QTS_Context'
QTS_CFG_GROUP_FILTERS = 'QTS_Filters'
QTS_CFG_GROUP_RESOURCES = 'QTS_Resources'
QTS_CFG_GROUP_ACCOUNTS = 'QTS_Accounts'
QTS_CFG_GROUP_ALGOES = 'QTS_Algoes'
QTS_CFG_GROUP_CALCULATES = 'QTS_Calculates'
QTS_CFG_GROUP_CHECKS = 'QTS_Checks'
QTS_CFG_GROUP_EXCHANGES = 'QTS_Exchanges'
QTS_CFG_GROUP_LOGICS = 'QTS_Logics'
QTS_CFG_GROUP_PARSERS = 'QTS_Parsers'
QTS_CFG_GROUP_SECUINFOES = 'QTS_SecuInfoes'
QTS_CFG_GROUP_STRATEGIES = 'QTS_Strategies'
QTS_CFG_GROUP_TRANSFERS	= 'QTS_Transfers'
QTS_CFG_GROUP_LOGS = 'QTS_Logs'
QTS_CFG_GROUP_BACKUPS = 'QTS_Backups'
QTS_CFG_GROUP_LOADERS = 'QTS_Loaders'
QTS_CFG_GROUP_POSITIONS	= 'QTS_Positions'
QTS_CFG_GROUP_EXPOSITIONS	= 'QTS_ExPositions'
QTS_CFG_GROUP_MARKETS = 'QTS_Markets'
QTS_CFG_GROUP_DSTRANSFERS = 'QTS_DSTransfers'
QTS_CFG_GROUP_GUITRANSFERS = 'QTS_GUITransfers'
QTS_CFG_GROUP_GWTRANSFERS = 'QTS_GWTransfers'
QTS_CFG_GROUP_MQTRANSFERS = 'QTS_MQTransfers'
QTS_CFG_GROUP_CKTRANSFERS = 'QTS_CKTransfers'
QTS_CFG_GROUP_CPTRANSFERS = 'QTS_CPTransfers'
QTS_CFG_GROUP_ERRORS = 'QTS_Errors'
QTS_CFG_GROUP_PROPERTYS = 'QTS_Propertys'
QTS_CFG_GROUP_MONITORS = QTS_CFG_GROUP_MQTRANSFERS

QTS_CFG_PLUGINS_APP = 'QTS_App_Plugins'
QTS_CFG_PLUGINS_CONTEXT = 'QTS_Context_Plugins'
QTS_CFG_PLUGINS_FILTERS = 'QTS_Filters_Plugins'
QTS_CFG_PLUGINS_ACCOUNTS = 'QTS_Accounts_Plugins'
QTS_CFG_PLUGINS_ALGOES = 'QTS_Algoes_Plugins'
QTS_CFG_PLUGINS_CALCULATES = 'QTS_Calculates_Plugins'
QTS_CFG_PLUGINS_CHECKS = 'QTS_Checks_Plugins'
QTS_CFG_PLUGINS_EXCHANGES = 'QTS_Exchanges_Plugins'
QTS_CFG_PLUGINS_LOGICS = 'QTS_Logics_Plugins'
QTS_CFG_PLUGINS_PARSERS = 'QTS_Parsers_Plugins'
QTS_CFG_PLUGINS_SECUINFOES = 'QTS_SecuInfoes_Plugins'
QTS_CFG_PLUGINS_STRATEGIES = 'QTS_Strategies_Plugins'
QTS_CFG_PLUGINS_TRANSFERS	= 'QTS_Transfers_Plugins'
QTS_CFG_PLUGINS_LOGS = 'QTS_Logs_Plugins'
QTS_CFG_PLUGINS_BACKUPS = 'QTS_Backups_Plugins'
QTS_CFG_PLUGINS_LOADERS = 'QTS_Loaders_Plugins'
QTS_CFG_PLUGINS_POSITIONS	= 'QTS_Positions_Plugins'
QTS_CFG_PLUGINS_MARKETS = 'QTS_Markets_Plugins'
QTS_CFG_PLUGINS_DSTRANSFERS = 'QTS_DSTransfers_Plugins'
QTS_CFG_PLUGINS_GUITRANSFERS = 'QTS_GUITransfers_Plugins'
QTS_CFG_PLUGINS_GWTRANSFERS = 'QTS_GWTransfers_Plugins'
QTS_CFG_PLUGINS_MQTRANSFERS = 'QTS_MQTransfers_Plugins'
QTS_CFG_PLUGINS_CKTRANSFERS = 'QTS_CKTransfers_Plugins'
QTS_CFG_PLUGINS_CPTRANSFERS = 'QTS_CPTransfers_Plugins'
QTS_CFG_PLUGINS_ERRORS = 'QTS_Errors_Plugins'
QTS_CFG_PLUGINS_PROPERTYS = 'QTS_Property_Plugins'
QTS_CFG_PLUGINS_MONITORS = QTS_CFG_PLUGINS_MQTRANSFERS

QTS_APP_IDENTITY_KEY='Qts_App_Identity'
QTS_APP_MODE_KEY='Qts_App_Mode'

QTS_LOG_DEFAULT_KEY='default_log'
QTS_LOG_DEFAULT_NAME='default'

QTS_CFG_PLUGINS_SECUINFOES_STATIC='Qts_SecuInfoes_Static'
QTS_CFG_PLUGINS_SECUINFOES_DYNAMIC='Qts_SecuInfoes_Dynamic'
QTS_CFG_LANGUAGE='Qts_Cfg_Language'

QTS_LOG_DEFAULT_LIB='QtsTxtLog'
QTS_LOG_DEFAULT_FUN='CreateLog'
QTS_ENTRY_PYFILE='entry'
QTS_PROTO_FILE='qtsgproto.proto'
QTS_SYSTEM_WINDOWS_STR='win32'

QTS_APP_WINDOWS_DEBUG='Debug'
QTS_APP_WINDOWS_RELEASE='Release'
QTS_APP_LINUX_DEBUG=''
QTS_APP_LINUX_RELEASE=''

QTS_APP_PY_VERSION_KEY='QTS_APP_PY_VERSION'
QTS_APP_RUN_VERSION_RELEASE_STR='release'
QTS_APP_RUN_VERSION_DEBUG_STR='debug'
QTS_APP_RUN_VERSION_PUBLISH_STR='publish'

QTS_CFG_SUFIX_INSTRUMENT='Instrument'
QTS_CFG_SUFIX_PARAMETER='Parameter'
QTS_CFG_SUFIX_COMMENT='Comment'
QTS_CFG_SUFIX_COMMAND='Command'

QTS_CFG_APP_IP_ADDR='QTS_CFG_{0}_IP_{1}'
QTS_CFG_APP_IP_PORT='QTS_CFG_{0}_PORT_{1}'

QTS_CFG_START_SINGLE_APP='Qts_Cfg_Start_Single_App'
QTS_CFG_APP_DS_NAME='DS'
QTS_CFG_APP_GW_NAME='GW'
QTS_CFG_APP_SS_NAME='SS'
QTS_CFG_APP_GUI_NAME='GUI'

QTS_CFG_APP_DS_IP_NAME=QTS_CFG_APP_DS_NAME
QTS_CFG_APP_GW_IP_NAME=QTS_CFG_APP_GW_NAME
QTS_CFG_APP_SS_IP_NAME=QTS_CFG_APP_SS_NAME
QTS_CFG_APP_GUI_IP_NAME=QTS_CFG_APP_GUI_NAME

QTS_TRACE_MESSAGE='Qts_Trace_Message'
QTS_TRACE_DEBUG='Qts_Trace_Debug'
QTS_TRACE_WARNING='Qts_Trace_Warning'
QTS_TRACE_ERROR='Qts_Trace_Error'

QTS_LOG_MESSAGE='Qts_Log_Message'
QTS_LOG_DEBUG='Qts_Log_Debug'
QTS_LOG_WARNING='Qts_Log_Warning'
QTS_LOG_ERROR='Qts_Log_Error'

QTS_CMD_CFG_KEY='--cfg'
QTS_EVN_FILE_KEY='--envfile'
QTS_TRACE_MESSAGE_KEY='--tracemessage'
QTS_TRACE_DEBUG_KEY='--tracedebug'
QTS_TRACE_WARNING_KEY='--tracewarning'
QTS_TRACE_ERROR_KEY='--traceerror'

QTS_LOG_MESSAGE_KEY='--logmessage'
QTS_LOG_DEBUG_KEY='--logdebug'
QTS_LOG_WARNING_KEY='--logwarning'
QTS_LOG_ERROR_KEY='--logerror'

############################################################################
#entry py file cfg
QTS_App_Variables='Qts_App_Variables'
QTS_Py_Variables='Qts_Py_Variables'
QTS_IS_PRINT='Qts_Is_Print'
QTS_APP_SYSTEM='Qts_App_System'
QTS_RUN_VERSION='Qts_Run_Version'
QTS_APP_VERSION='Qts_App_Version'
QTS_APP_VERSION_STR='Qts_App_Version_Str'
QTS_BASE_PATH='Qts_Base_Path'
QTS_BASE_PATH_KEY='QTS_BASE_PATH'
QTS_LIB_PATH='Qts_Lib_Path'
QTS_CFG_PATH='Qts_Cfg_Path'
QTS_REPLAY_PATH='Qts_Replay_Path'
QTS_REPLAY_PATH_KEY='QTS_REPLAY_PATH'
QTS_USER_STRATEGY_PATH='Qts_User_Strategy_Path'
QTS_USER_MARKET_PATH='Qts_User_Market_Path'
QTS_USER_EXCHANGE_PATH='Qts_User_Exchange_Path'
QTS_APP_PATH='Qts_App_Path'
QTS_APP_DEFAULT_PATH='Qts_App_Default_Path'

QTS_LOADER_TYPE='Qts_Loader_Type'
QTS_BACKUP_TYPE='Qts_Backup_Type'
QTS_REPLAY_TYPE='Qts_Replay_Type'
QTS_MULTI_THREAD='Qts_Multi_Thread'

QTS_IS_DS_MONITOR='Qts_Is_DS_Monitor'
QTS_IS_GW_MONITOR='Qts_Is_GW_Monitor'
QTS_IS_SS_MONITOR='Qts_Is_SS_Monitor'
QTS_IS_GUI_MONITOR='Qts_Is_GUI_Monitor'
QTS_MONITOR_WAIT_TIME='Qts_Monitor_Wait_Time'

QTS_IS_REPLAY='Qts_Is_Replay'
QTS_IS_MATCH='Qts_Is_Match'

QTS_CONVERT_CFG_FILE='qtsconvert'
QTS_QUERY_CFG_FILE='qtsquery'
QTS_GUI_CFG_FILE='qtsgui'
QTS_SS_CFG_FILE='qtsss'
QTS_DS_CFG_FILE='qtsds'
QTS_GW_CFG_FILE='qtsgw'

QTS_REPLAY_START_DATE='Qts_Replay_Start_Date'
QTS_REPLAY_END_DATE='Qts_Replay_End_Date'
QTS_REPLAY_START_TIME='Qts_Replay_Start_Time'
QTS_REPLAY_END_TIME='Qts_Replay_End_Time'

QTS_TRUE_STR='true'
QTS_FALSE_STR='false'

QTS_DATA_APP_FOLDER='QTS_DATA_APP_FOLDER'
QTS_CFG_APP_FOLDER='QTS_CFG_APP_FOLDER'
QTS_CSV_FLAG = ','

############################################################################
QTS_LOADER_FILE_INFO_S = 'qtsinfo_s'
QTS_LOADER_FILE_INFO_D = 'qtsinfo_d'

QTS_LOADER_FILE_ACCOUNT_TRADE = 'qtstrade'
QTS_LOADER_FILE_ACCOUNT_USER = 'qtsuser'
QTS_LOADER_FILE_ACCOUNT_EXCHANGE = 'qtsex'

QTS_LOADER_FILE_POSITION_TRADE = 'qtstrposition'
QTS_LOADER_FILE_POSITION_EXCHANGE = 'qtsexposition'
QTS_LOADER_GW_TRADE_POSITION = 'qts_trposition'

QTS_BACKUP_GW_TRADE_RECORD = 'trrecord'
QTS_BACKUP_GW_TRADE_POSITION = 'trposition'
QTS_BACKUP_GW_TRADE_ACCOUNT = 'traccount'
QTS_BACKUP_GW_TRADE_WORKING = 'gwworking'
QTS_BACKUP_GW_TRADE_CHILD_RECORD = 'gwftrecord'

QTS_BACKUP_GW_EXCHANGE_RECORD = 'exrecord'
QTS_BACKUP_GW_EXCHANGE_POSITION = 'exposition'
QTS_BACKUP_GW_EXCHANGE_ACCOUNT = 'exaccount'
QTS_BACKUP_GW_EXCHANGE_WORKING = 'exworking'

QTS_BACKUP_SS_STRATEGY = 'strategy'
QTS_BACKUP_SS_PARAMETER = 'parameter'
QTS_BACKUP_SS_WORKING = 'ssworking'

############################################################################
qts_db_prefix='qts_'
qts_market_field='qts_market'
qts_category_field='qts_category'
qts_viraccount_field='qts_viraccount'
qts_relaccount_field='qts_relaccount'
qts_sharetag_field='qts_sharetag'
qts_totalamount_field='qts_totalamount'
qts_avlamount_field='qts_avlamount'
qts_freezeamount_field='qts_freezeamount'
qts_currency_field='qts_currency'
qts_date_field='qts_date'
qts_user_field='qts_user'
qts_subaccount_field='qts_subaccount'
qts_code_field='qts_code'
qts_type_field='qts_type'
qts_level_field='qts_level'
qts_totalvol_field='qts_totalvol'
qts_avlvol_field='qts_avlvol'
qts_toalcost_field='qts_toalcost'
qts_qtsdate_field='qts_qtsdate'
qts_avlcredempvol_field='qts_avlcredempvol'
qts_todayvol_field='qts_todayvol'
qts_secucode_field='qts_secucode'
qts_ordercode_field='qts_ordercode'
qts_marketname_field='qts_marketname'
qts_categoryname_field='qts_categoryname'
qts_secuname_field='qts_secuname'
qts_minorderqty_field='qts_minorderqty'
qts_maxorderqty_field='qts_maxorderqty'
qts_pricetick_field='qts_pricetick'
qts_tradetype_field='qts_tradetype'
qts_postype_field='qts_postype'
qts_multipler_field='qts_multipler'
qts_margin_field='qts_margin'
qts_lastprice_field='qts_lastprice'
qts_lolimitedprice_field='qts_lolimitprice'
qts_uplimitedprice_field='qts_uplimitprice'
qts_suspension_field='qts_suspension'
qts_tradingfee_field='qts_tradingfee'
qts_strategyid_field='qts_strategyid'
qts_name_field='qts_name'
qts_account_field='qts_account'
qts_minorderid_field='qts_minorderid'
qts_maxorderid_field='qts_maxorderid'
qts_orderidstep_field='qts_orderidstep'
qts_status_field='qts_status'
qts_threadid_field='qts_threadid'
qts_key_field='qts_key'
qts_codetype_field='qts_codetype'
qts_index_field='qts_index'
qts_mode_field='qts_mode'
qts_component_field='qts_component'
qts_style_field='qts_style'
qts_value_field='qts_value'
qts_vardecimal_field='qts_vardecimal'
qts_save_field='qts_save'
qts_modify_field='qts_modify'
qts_secuid_field='qts_secuid'
qts_orderid_field='qts_orderid'
qts_algoid_field='qts_algoid'
qts_algoindex_field='qts_algoindex'
qts_parentid_field='qts_parentid'
qts_action_field='qts_action'
qts_paction_field='qts_paction'
qts_prevstatus_field='qts_prevstatus'
qts_oprice_field='qts_oprice'
qts_iprice_field='qts_iprice'
qts_ovolume_field='qts_ovolume'
qts_ivolume_field='qts_ivolume'
qts_otime_field='qts_otime'
qts_itime_field='qts_itime'
qts_property_field='qts_property'
qts_canceled_field='qts_canceled'
qts_userid_field='qts_userid'
qts_refid_field='qts_refid'
qts_sessionid_field='qts_sessionid'
qts_workingvol_field='qts_workingvol'
qts_workingsize_field='qts_workingsize'
qts_ordervol_field='qts_ordervol'
qts_ordersize_field='qts_ordersize'
qts_cancelvol_field='qts_cancelvol'
qts_cancelsize_field='qts_cancelsize'
qts_unackedvol_field='qts_unackedvol'
qts_unackedsize_field='qts_unackedsize'
qts_avprice_field='qts_avprice'
qts_amount_field='qts_amount'
qts_appid_field='qts_appid'
qts_apptype_field='qts_apptype'
qts_version_field='qts_version'
qts_group_field='qts_group'
qts_price_field='qts_price'
qts_localid_field='qts_localid'
qts_localport_field='qts_localport'
qts_remoteid_field='qts_remoteid'
qts_remoteport_field='qts_remoteport'
qts_currorderid_field='qts_currorderid'
qts_cycle_field='qts_cycle'
qts_tradecycle_field='qts_tradecycle'
qts_ismanual_field='qts_ismanual'
qts_decimal_field='qts_decimal'
qts_totalcost_field='qts_totalcost'
qts_tradetn_field='qts_tradetn'
qts_posmode_field='qts_posmode'
qts_settlementprice_field='qts_settlementprice'
qts_direction_field='qts_direction'
qts_source_field='qts_source'
qts_autoid_field='qts_autoid'
qts_id_field='qts_id'
qts_expiry_field='qts_expiry'
qts_right_field='qts_right'
qts_strike_field='qts_strike'
qts_tradingclass_field='qts_tradingclass'
qts_host_field='qts_host'
qts_password_field='qts_password'
qts_detail_field='qts_detail'
qts_ss_field='qts_ss'
qts_gw_field='qts_gw'
qts_position_field='qts_position'
qts_path_field='qts_path'
qts_machineid_field='qts_machineid'
qts_file_field='qts_file'
qts_command_field='qts_command'

#add by lay sta
qts_rights_table='qts_rights'
qts_target_field='qts_target'
qts_read_field='qts_read'
qts_insert_field='qts_insert'
qts_delete_field='qts_delete'
qts_update_field='qts_update'

qts_manager_field='qts_manager'
qts_bdate_field='qts_bdate'
qts_edate_field='qts_edate'
qts_productid_field='qts_productid'

#add by lay end

qts_json_id_field='id'
qts_json_parent_field='_parentId'
qts_json_state_field='state'
qts_json_rows_field='rows'
qts_json_total_field='total'
qts_json_page_field='page'
qts_json_inserted='inserted'
qts_json_deleted='deleted'
qts_json_updated='updated'
qts_json_dbname_field='dbname'
qts_web_get_field='GET'
qts_web_post_field='POST'

#backup table name
qts_positions_table='qts_positions'
qts_accounts_table='qts_accounts'
qts_records_table='qts_records'
qts_workings_table='qts_workings'
qts_remotes_table='qts_remotes'
qts_books_table='qts_books'
qts_strategys_table='qts_strategys'
qts_parameters_table='qts_parameters'
qts_controls_table='qts_controls'
qts_messages_table='qts_messages'
qts_datas_table='qts_datas'
qts_pnls_table='qts_pnls'

#config and loader table name
qts_secuinfo_s_table='qts_secuinfo_s'
qts_secuinfo_d_table='qts_secuinfo_d'
qts_apps_table='qts_apps'
qts_jobs_table='qts_jobs'
qts_jobdeploys_table='qts_jobdeploys'
qts_products_table='qts_products'
qts_machines_table='qts_machines'
qts_strategyinapp_table='qts_strategyinapp'
qts_strategyinproduct_table='qts_strategyinproduct'
qts_trade_table='qts_trade'
qts_user_table='qts_user'
qts_exchange_table='qts_exchange'
qts_position_table='qts_position'
qts_strategy_table='qts_strategy'
qts_instrument_table='qts_instrument'
qts_parameter_table='qts_parameter'
qts_comment_table='qts_comment'
qts_command_table='qts_command'



#database name
qts_gw_backup_db='qts_gw_backup'
qts_ss_backup_db='qts_ss_backup'
qts_config_db='qts_config'
qts_loader_db='qts_loader'

qts_secuinfo_middle_csv='qts_secuinfo.csv'
qts_secuinfo_s_file='qtsinfo_s.info'
qts_secuinfo_d_file='qtsinfo_d.info'
qts_get_secuinfo_file='runc_secuinfo.sh'
qts_convert_backup_file='runc_convert.sh'
qts_convert_secuinfo_cmd='qtsconvertsecuinfo.py'
qts_clearing_position_cmd='qtsconvertaccount.py'
qts_clearing_account_cmd='qtsconvertaccount.py'

############################################################################
